export const extensionToGrammar = new Map([
  // Web / Frontend
  ['.ts', 'typescript'],
  ['.tsx', 'tsx'],
  ['.js', 'javascript'],
  ['.jsx', 'javascript'],
  ['.vue', 'vue'],
  ['.html', 'html'],
  ['.css', 'css'],
  // Backend / Systems
  ['.py', 'python'],
  ['.go', 'go'],
  ['.rs', 'rust'],
  ['.java', 'java'],
  ['.kt', 'kotlin'],
  ['.scala', 'scala'],
  ['.rb', 'ruby'],
  ['.php', 'php'],
  ['.cs', 'c_sharp'],
  // Native
  ['.c', 'c'],
  ['.h', 'c'],
  ['.cpp', 'cpp'],
  ['.hpp', 'cpp'],
  ['.swift', 'swift'],
  ['.zig', 'zig'],
  ['.dart', 'dart'],
  ['.elm', 'elm'],
  ['.sol', 'solidity'],
  // Scripting / Config
  ['.sh', 'bash'],
  ['.bash', 'bash'],
  ['.zsh', 'bash'],
  ['.lua', 'lua'],
  ['.pl', 'perl'],
  ['.r', 'r'],
  ['.json', 'json'],
  ['.yaml', 'yaml'],
  ['.yml', 'yaml'],
  ['.toml', 'toml'],
  // Functional
  ['.ex', 'elixir'],
  ['.exs', 'elixir'],
  ['.hs', 'haskell'],
  ['.ml', 'ocaml'],
  ['.mli', 'ocaml'],
])

export const symbolNodeTypes = new Set([
  // TypeScript / JavaScript
  'function_declaration',
  'function_expression',
  'arrow_function',
  'method_definition',
  'class_declaration',
  'interface_declaration',
  'type_alias_declaration',
  'enum_declaration',
  'variable_declarator',
  'lexical_declaration',
  // Python
  'function_definition',
  'class_definition',
  'assignment',
  // Go
  'function_item',
  'struct_item',
  'type_declaration',
  // Rust
  'function_item',
  'struct_item',
  'impl_item',
  'trait_item',
  'enum_item',
  // Java / Kotlin / C# / Scala
  'method_declaration',
  'constructor_declaration',
  'field_declaration',
  // Ruby
  'method',
  'singleton_method',
  // PHP
  'function_definition',
  // C / C++
  'function_definition',
  'struct_specifier',
  // Dart
  'class_definition',
  'function_signature',
  // Solidity
  'contract_declaration',
  'function_definition',
  'event_definition',
  // Elixir
  'call', // def, defmodule often parsed as call
  // Elm
  'value_declaration',
  'type_declaration',
  // Ruby
  'method',
  'class',
  'module',
  // General
  'export_statement',
])

export const keywords = new Set([
  'def',
  'fn',
  'func',
  'module',
  'package',
  'using',
  'use',
  'if',
  'else',
  'for',
  'while',
  'do',
  'switch',
  'case',
  'break',
  'continue',
  'return',
  'function',
  'class',
  'const',
  'let',
  'var',
  'import',
  'export',
  'default',
  'from',
  'as',
  'async',
  'await',
  'try',
  'catch',
  'finally',
  'throw',
  'new',
  'this',
  'super',
  'extends',
  'implements',
  'interface',
  'type',
  'enum',
  'public',
  'private',
  'protected',
  'static',
  'readonly',
  'abstract',
  'override',
  'void',
  'null',
  'undefined',
  'true',
  'false',
  'typeof',
  'instanceof',
  'in',
  'of',
  'delete',
  'yield',
  'get',
  'set',
])
